### ISSUE TITLE
distance error:

### ISSUE THREAD

**Issue by zhunnan** [kxhit/SG_PR#7]
I test pair_file: ["/SG_PR_DATA/graphs_sk/05/000000.json","/SG_PR_DATA/graphs_sk/05/000006.json"] in eval_pair.py.
The rusult score more than 1.
------------------------------------------------------------------------------console output:
Enumerating unique labels.

{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11}
12
loading model:  ./model/model.pth
distance error:  3.3904110318197205
-----------------------------------------------------------------------------------------------------
I,m confused.

**Comment by kxhit** [comment]
It throws an error from the code [here](https://github.com/kxhit/SG_PR/blob/47e995ea76c2229f8ba62b1fb33b9aeb13503eeb/sg_net.py#L308). Because the distance between the two scenes (000000 and 000006) is between 3m-20m, which is not considered as explained in our paper. You can change the code [here](https://github.com/kxhit/SG_PR/blob/47e995ea76c2229f8ba62b1fb33b9aeb13503eeb/sg_net.py#L308) to measure each two scenes similarity anyhow. Let me know if you have other confusions.

**Comment by zhunnan** [comment]
In xxx.json, how to get the pose data?  If I only get topo point and it's label of every frame (in your work ,refers to [centers] and [nodes]), can I get similar score between two any frames without pose?
I 'd like to test a sequese in this way. Thanks for your answer!

**Comment by kxhit** [comment]
Pose data is from KITTI dataset and you can get similar score between two any frames without pose as we don't need pose in infer. Pose data is only used for evaluation and training as we need pose to define which pair is positive (distance less 3m) and which is negative (distance over 20m). 
You can modify the code and give fake pose (e.g. 000) in inference to obtain the similar score regardless of their true related pose. However, in this way you may not know the two pair is a real loop closure or not.

**Comment by zhunnan** [comment]
Nice
