### ISSUE TITLE
A question about the code in sg_net.py

### ISSUE THREAD

**Issue by cloudcjf** [kxhit/SG_PR#8]
Hi, thanks for your interesting work! I'm going deep into the code and have a question in line 326 of sg_net.py. The code is as below.  In my opinion,  batch_feature_1 should be the concatenated feature of one frame. So as  batch_feature_2. For what reason makes you append data["features_2"] into batch_feature_1? Tell me if I miss any point. Thanks again for your reply.
for graph_pair in batch:
            data = process_pair(graph_pair)
            data = self.transfer_to_torch(data, training)
            batch_feature_1.append(data["features_1"])
            batch_feature_2.append(data["features_2"])
            batch_feature_1.append(data["features_2"])
            batch_feature_2.append(data["features_1"])
            target = data["target"]
            batch_target.append(target)
            batch_target.append(target)

**Comment by kxhit** [comment]
Thanks for your interest to our work! 

We found the NTN module asymmetric to the input pair that means if we exchange the pair order (e.g., [input1: scene0001 and input2: scene0080] VS [input1:scene0080 and input2: scene0001]), the output similarity score is different. This is wrong as we hope for a pair the similarity should be consistent regardless their input order. So we append the feature and target again to train the network to fix this problem. 

Well I think a better way is to modify the network structure to ensure the output is order-invariant to the input rather than do data augmentation by appending. Let me know if I make it clear.

**Comment by cloudcjf** [comment]
Thanks for your response! Yeah, your explanation is quite clear. I will close this issue.

**Comment by YangSiri** [comment]
Hi, @kxhit  

Is there a duplication of func _eval_batch_pair_ in the 459 and 503 row of _sg_net.py_ ?

[    def eval_batch_pair(self, batch):](https://github.com/kxhit/SG_PR/blob/ec94d961573c80234d2a2d13bf730d59dbd723b6/sg_net.py#L459)

**Comment by kxhit** [comment]
Hi @YangSiri  

Thanks for pointing it out. Yeah, there is some dead code. Sorry for not cleaning the code well.
